create table category (id bigint generated by default as identity, description varchar(255), primary key (id))
create table category_recipes (category_id bigint not null, recipes_id bigint not null, primary key (category_id, recipes_id))
create table ingredient (id bigint generated by default as identity, amount decimal(19,2), description varchar(255), recipe_id bigint, unit_of_measure_id bigint, primary key (id))
create table notes (id bigint generated by default as identity, recipe_notes clob, recipe_id bigint, primary key (id))
create table recipe (id bigint generated by default as identity, cook_time integer, description varchar(255), difficulty varchar(255), directions varchar(255), image blob, prep_time integer, servings integer, source varchar(255), url varchar(255), primary key (id))
create table recipe_category (recipe_id bigint not null, category_id bigint not null, primary key (recipe_id, category_id))
create table recipe_ingredients (recipe_id bigint not null, ingredients_id bigint not null, primary key (recipe_id, ingredients_id))
create table unit_of_measure (id bigint generated by default as identity, description varchar(255), primary key (id))
alter table recipe_ingredients add constraint UK_adlqiu427fu7igg7385el0xjh unique (ingredients_id)
alter table category_recipes add constraint FKh48plx4pt6sd122piao8xot1u foreign key (recipes_id) references recipe
alter table category_recipes add constraint FKd0bswler7xyafar8pt4ob4isa foreign key (category_id) references category
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe
alter table ingredient add constraint FK15ttfoaomqy1bbpo251fuidxw foreign key (unit_of_measure_id) references unit_of_measure
alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe
alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category
alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe
alter table recipe_ingredients add constraint FKg8ssng1dqiwgcptjptldels74 foreign key (ingredients_id) references ingredient
alter table recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe
create table category (id bigint generated by default as identity, description varchar(255), primary key (id))
create table ingredient (id bigint generated by default as identity, amount decimal(19,2), description varchar(255), recipe_id bigint, unit_of_measure_id bigint, primary key (id))
create table notes (id bigint generated by default as identity, recipe_notes clob, recipe_id bigint, primary key (id))
create table recipe (id bigint generated by default as identity, cook_time integer, description varchar(255), difficulty varchar(255), directions varchar(255), image blob, prep_time integer, servings integer, source varchar(255), url varchar(255), primary key (id))
create table recipe_category (recipe_id bigint not null, category_id bigint not null, primary key (recipe_id, category_id))
create table recipe_ingredients (recipe_id bigint not null, ingredients_id bigint not null, primary key (recipe_id, ingredients_id))
create table unit_of_measure (id bigint generated by default as identity, description varchar(255), primary key (id))
alter table recipe_ingredients add constraint UK_adlqiu427fu7igg7385el0xjh unique (ingredients_id)
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe
alter table ingredient add constraint FK15ttfoaomqy1bbpo251fuidxw foreign key (unit_of_measure_id) references unit_of_measure
alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe
alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category
alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe
alter table recipe_ingredients add constraint FKg8ssng1dqiwgcptjptldels74 foreign key (ingredients_id) references ingredient
alter table recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe
create table category (id bigint generated by default as identity, description varchar(255), primary key (id))
create table ingredient (id bigint generated by default as identity, amount decimal(19,2), description varchar(255), recipe_id bigint, unit_of_measure_id bigint, primary key (id))
create table notes (id bigint generated by default as identity, recipe_notes clob, recipe_id bigint, primary key (id))
create table recipe (id bigint generated by default as identity, cook_time integer, description varchar(255), difficulty varchar(255), directions varchar(255), image blob, prep_time integer, servings integer, source varchar(255), url varchar(255), primary key (id))
create table recipe_category (recipe_id bigint not null, category_id bigint not null, primary key (recipe_id, category_id))
create table recipe_ingredients (recipe_id bigint not null, ingredients_id bigint not null, primary key (recipe_id, ingredients_id))
create table unit_of_measure (id bigint generated by default as identity, description varchar(255), primary key (id))
alter table recipe_ingredients add constraint UK_adlqiu427fu7igg7385el0xjh unique (ingredients_id)
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe
alter table ingredient add constraint FK15ttfoaomqy1bbpo251fuidxw foreign key (unit_of_measure_id) references unit_of_measure
alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe
alter table recipe_category add constraint FKqsi87i8d4qqdehlv2eiwvpwb foreign key (category_id) references category
alter table recipe_category add constraint FKcqlqnvfyarhieewfeayk3v25v foreign key (recipe_id) references recipe
alter table recipe_ingredients add constraint FKg8ssng1dqiwgcptjptldels74 foreign key (ingredients_id) references ingredient
alter table recipe_ingredients add constraint FKhnsmvxdlwxqq6x2wbgnoef5gr foreign key (recipe_id) references recipe
